### ISSUE TITLE
Missing ConfigMgr Task Sequence Monitor Tool

### ISSUE THREAD

**Issue by Patel-Sheetal** [SMSAgentSoftware/ConfigMgr-Task-Sequence-Monitor#2]
Missing ConfigMgr Task Sequence Monitor Tool

**Comment by gwblok** [comment]
Blog Post: https://smsagent.blog/tools/configmgr-task-sequence-monitor/
Which points to TechNet, which is now deprecated and unavailable.  Was hoping to find the code here, but like others, can't find it.

**Comment by codaamok** [comment]
For now we're lucky enough to find it on the web archive: https://web.archive.org/web/20201112030450/https://gallery.technet.microsoft.com/ConfigMgr-Task-Sequence-fefdc532

**Comment by Patel-Sheetal** [comment]
Thank you very much codaamok for sharing the new link.

**Comment by SMSAgentSoftware** [comment]
Sorry guys, I never finished porting my Technet contributions to Github! I've added the MSI here as a release as well as the source code.
