### ISSUE TITLE
ConfigMGR Task Sequence Monitor v1.6.MSI

### ISSUE THREAD

**Issue by chaosisbliss** [SMSAgentSoftware/ConfigMgr-Task-Sequence-Monitor#3]
Hi Trevor,

I hope all is well with you. First off, I wanted to say thank you for the work you have done on the tools you provided for free to the public. I will never forgot the day I found the ConfigMGR Task Sequence Monitor v1.6.MSI on Tech Gallery. It has been fantastic. 

I am reaching out because the the .MSI can no longer be found. Tech Gallery is read only unfortunately. Is there any chance you have it and could make it available to download again?

**Comment by codaamok** [comment]
For now we're lucky enough to find it on the web archive: https://web.archive.org/web/20201112030450/https://gallery.technet.microsoft.com/ConfigMgr-Task-Sequence-fefdc532

**Comment by SMSAgentSoftware** [comment]
Thanks for the feedback. I realized I never finished porting my Technet contributions to Github! I added the MSI here as a release as well as the source code.
